
CREATE TABLE `ScoreRecord` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `UserID` INT 11 NOT NULL,
    `Score` INT 11 NOT NULL,
    `CreatedTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;